parameters:
    curlHelper.class:    Renaissance\CommonBundle\Tools\CurlHelper
    curlHelper.class.canvas_access_token:   HgT9BCJaOYDzWcgC7O9UYqYg0fcnIIb4uDchAF4pYklpJx29nPdHM6afbdhxwPzd
    curlHelper.class.base_url:   "http://localhost:3000/api/v1/"
    curlHelper.class.authed:   FALSE
services:
    curlHelper:
        class:    "%curlHelper.class%"
        arguments:    ["%curlHelper.class.canvas_access_token%","%curlHelper.class.base_url%","%curlHelper.class.authed%"]