parameters:
    curlHelper.class:    Renaissance\CommonBundle\Tools\CurlHelper
    curlHelper.class.canvas_access_token:   IxX0B5V61DTxuSiWhKVYR3BVFcLCkqhoIosZmnGT2rEbolWkXi6TdX2GaDmk06iq
    curlHelper.class.base_url:   "https://canvas.example.com/api/v1/"
services:
    curlHelper:
        class:    "%curlHelper.class%"
        arguments:    ["%curlHelper.class.canvas_access_token%","%curlHelper.class.base_url%","%curlHelper.class.authed%"]
