parameters:
    curlHelper.class:    Renaissance\CommonBundle\Tools\CurlHelper
    curlHelper.class.canvas_access_token:   jJZi3lVjNrRdlQ6v28c07CCs1rELcjsaE5S0PIUa1P3dTxS0k8h50tvOaIUpiIWt
    curlHelper.class.base_url:   "https://canvas.example.com/api/v1/"
    curlHelper.class.authed:   FALSE
services:
    curlHelper:
        class:    "%curlHelper.class%"
        arguments:    ["%curlHelper.class.canvas_access_token%","%curlHelper.class.base_url%","%curlHelper.class.authed%"]
