parameters:
    curlHelper.class:    Renaissance\CommonBundle\Tools\CurlHelper
    curlHelper.class.canvas_access_token:   zSQYbaW5bQlDXYJGAdWPjIUEb2DTAjwfVTUa0z2uF8ydL7bUuhlrXimwHQ1EYDhl
    curlHelper.class.base_url:   "http://localhost:3000/api/v1/"
    curlHelper.class.authed:   FALSE
services:
    curlHelper:
        class:    "%curlHelper.class%"
        arguments:    ["%curlHelper.class.canvas_access_token%","%curlHelper.class.base_url%","%curlHelper.class.authed%"]
