parameters:
    curlHelper.class:    Renaissance\CommonBundle\Tools\CurlHelper
    curlHelper.class.canvas_access_token:   reyl8K5cC1cGYIALNXayUyFC2k623o8XYOrtSd5dBSZ90JnPBLsfQdfJKFmyjBow
    curlHelper.class.base_url:   "http://localhost:3000/api/v1/"
    curlHelper.class.authed:   FALSE
services:
    curlHelper:
        class:    "%curlHelper.class%"
        arguments:    ["%curlHelper.class.canvas_access_token%","%curlHelper.class.base_url%","%curlHelper.class.authed%"]